/*
 * DownloadView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.awt.event.ActionEvent;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Date;

import javax.swing.JOptionPane;

import cn.wangshidai.entity.TaskDownloadInfo;
import cn.wangshidai.util.PublicUtil;

/**
 *
 * @author  __USER__
 */
public class DownloadView extends javax.swing.JInternalFrame {

	/** Creates new form DownloadView */
	public DownloadView() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();

		setClosable(true);
		setIconifiable(true);
		setTitle("\u4e0b\u8f7d\u4efb\u52a1");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u4e0b\u8f7d\u5730\u5740\uff1a");

		jButton1.setText("\u5f00\u59cb\u4e0b\u8f7d");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				buttonClick(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(64, 64, 64)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING,
												false)
												.addComponent(
														jButton1,
														javax.swing.GroupLayout.Alignment.LEADING,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addGroup(
														javax.swing.GroupLayout.Alignment.LEADING,
														layout.createSequentialGroup()
																.addComponent(
																		jLabel1)
																.addGap(27, 27,
																		27)
																.addComponent(
																		jTextField1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		373,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(63, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel1)
												.addComponent(
														jTextField1,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														43,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										41, Short.MAX_VALUE)
								.addComponent(jButton1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										44,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(26, 26, 26)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	
	private void buttonClick(ActionEvent event){
		
		String urlStr = this.jTextField1.getText();
		
		// 地址正则表达式格式
		String str = "(https?|ftp|file)://[-A-Za-z0-9+&@#/%?=~_|!:,.;]+[-A-Za-z0-9+&@#/%=~_|]";
		
		if(!urlStr.matches(str)){
			JOptionPane.showMessageDialog(null, "url不合法！！");
		}else{
			/////要判断用户输入的url地址是否资源存在！！！！  502  400  500  503
			///学到下一章【网络编程】再来优化 
			
			
			//在这里调用方法（这个执行任务流会在【主线程】执行！）
			//download(urlStr);
			TaskDownloadInfo task = new TaskDownloadInfo();
			task.setFile_url(urlStr);
			task.setFile_date(PublicUtil.getDateStr("yyyy-MM-dd", new Date()));
			String fileName = System.currentTimeMillis() + urlStr.substring(urlStr.lastIndexOf("."));
			task.setFile_name(fileName);
			
			task.start();//调用它的run方法
			
			
			//将该对象加入集合
			PublicUtil.wangshidaiList.add(task);
		}
		
		
	}
	
	
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	// End of variables declaration//GEN-END:variables

}