/*
 * MainView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;

import cn.wangshidai.entity.TaskDownloadInfo;
import cn.wangshidai.util.PublicUtil;

/**
 *
 * @author __USER__
 */
public class MainView extends javax.swing.JFrame {

	private int seconds = 5;
	
	/** Creates new form MainView */
	public MainView() {
		// 初始化控件（窗口上的一些效果）
		initComponents();

		// 默认全屏-窗口最大化
		this.setExtendedState(JFrame.MAXIMIZED_BOTH);
		
		
		//从文件中读取数据
		getWangshidaiList();
		
		
		//刷新title
		refreshThread();
		
	}

	
	public static void getWangshidaiList(){
		
		ObjectInputStream input = null;
		try {
			File file = new File(PublicUtil.DB_FILE);
			if(file.exists()){//如果文件存在！！
				input = new ObjectInputStream(new FileInputStream(file));
				PublicUtil.wangshidaiList = (List<TaskDownloadInfo>) input.readObject();
			}
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			try {
				if(input!=null){
					input.close();
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		
		
	}
	
	
	// 开启一条子线程去保存数据
	private void refreshThread() {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				while (true) {
					//loadTable();
					if(seconds<=0){
						seconds = 5;
						setTitle("【网时代下载任务管理器】正在保存数据...");
						//保存数据
						writeData(PublicUtil.wangshidaiList);
						
						try {
							Thread.sleep(2000);
						} catch (InterruptedException e) {
							// TODO Auto-generated catch block
							e.printStackTrace();
						}
					}
					
					titleText();
					seconds--;
					

					try {
						Thread.sleep(1000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			}
		});
		thread.setDaemon(true);
		thread.start();
	}

	
	private void titleText(){
		this.setTitle("【网时代下载任务管理器】"+this.seconds+"秒后将会自动保存数据");
	}
	
	
	public void writeData(Object obj){
		ObjectOutputStream out = null;
		try {
			
			File file = new File(PublicUtil.DB_FILE);
			if(!file.exists()){
				file.getParentFile().mkdirs();
			}
			
			out = new ObjectOutputStream(new FileOutputStream(file));
			out.writeObject(obj);
			
			
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			try {
				out.close();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	
	
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jDesktopPane1 = new javax.swing.JDesktopPane();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenuItem1 = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jMenuItem3 = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jMenu1.setText("\u67e5\u770b\u4efb\u52a1\u5217\u8868");

		jMenuItem1.setText("\u6b63\u5728\u4e0b\u8f7d");
		jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem1ActionPerformed(evt);
			}
		});
		jMenu1.add(jMenuItem1);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("\u4e0b\u8f7d");
		jMenu2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// jMenu2ActionPerformed(evt);
			}
		});

		jMenuItem3.setText("\u5f00\u59cb\u4e0b\u8f7d");
		jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jMenuItem3ActionPerformed(evt);
			}
		});
		jMenu2.add(jMenuItem3);

		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
				Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {
		DownloadView view = new DownloadView();
		view.setVisible(true);
		this.jDesktopPane1.add(view);
	}

	/*
	 * 菜单（正在下载）
	 */
	private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {
		SelectDownloadingView view = new SelectDownloadingView();
		view.setVisible(true);
		this.jDesktopPane1.add(view);

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JMenuItem jMenuItem1;
	private javax.swing.JMenuItem jMenuItem3;
	// End of variables declaration//GEN-END:variables

}