/*
 * SelectDownloadingView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.sound.midi.MidiDevice.Info;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import cn.wangshidai.entity.TaskDownloadInfo;
import cn.wangshidai.util.PublicUtil;

/**
 *
 * @author __USER__
 */
public class SelectDownloadingView extends javax.swing.JInternalFrame {

	private boolean isRefresh = true; 		// 是否需要刷新
	private int tableSelectedIndex = -1;	// table的选择行下标
	TaskDownloadInfo info = new TaskDownloadInfo();
	

	/** Creates new form SelectDownloadingView */
	public SelectDownloadingView() {
		initComponents();

		// 加载表格数据
		refreshThread();

	}

	// 开启一条子线程去刷新表格
	private void refreshThread() {
		Thread thread = new Thread(new Runnable() {
			@Override
			public void run() {
				while (isRefresh) {
					loadTable();

					try {
						Thread.sleep(1000);
					} catch (InterruptedException e) {
						// TODO Auto-generated catch block
						e.printStackTrace();
					}
				}
			}
		});
		thread.setDaemon(true);
		thread.start();
	}

	private void loadTable() {
		DefaultTableModel tableModel = (DefaultTableModel) this.jTable1
				.getModel();

		while (tableModel.getRowCount() > 0) {
			tableModel.removeRow(0);
		}

		// 序号 文件名 日期 大小 状态
		for (int i = 0; i < PublicUtil.wangshidaiList.size(); i++) {
			TaskDownloadInfo info = PublicUtil.wangshidaiList.get(i);

			String statusStr = info.isIs_ok() ? "已完成" : "下载中";
			if (info.isIs_pause()) {
				String paswString = "暂停中";
				Object[] array = { i + 1, info.getFile_name(), info.getFile_date(),
						info.getFile_size(), paswString };
				tableModel.addRow(array);
			}else {
				Object[] array = { i + 1, info.getFile_name(), info.getFile_date(),
						info.getFile_size(), statusStr };
				tableModel.addRow(array);
			}

			
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		// “暂停”点击事件
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				pauseClick(evt);
			}
		});

		// 删除任务点击事件
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				deleteClick(evt);
			}
		});

		setClosable(true);
		setIconifiable(true);
		setTitle("\u67e5\u770b\u4e0b\u8f7d\u4e2d\u7684\u4efb\u52a1\u5217\u8868");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "序号", "文件名", "日期", "大小", "状态" }));
		jScrollPane1.setViewportView(jTable1);

		// 给Table绑定一个鼠标点击事件
		jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jTable1MousePressed(evt);
			}
		});

		jPanel1.setBorder(javax.swing.BorderFactory
				.createTitledBorder("\u4efb\u52a1\u8be6\u60c5"));

		jLabel1.setText("\u6587\u4ef6\u540d");

		jTextField1.setEnabled(false);

		jLabel2.setText("\u5927\u5c0f");

		jTextField2.setEnabled(false);

		jLabel3.setText("\u72b6\u6001");

		jTextField3.setEnabled(false);

		jLabel4.setText("\u65e5\u671f");

		jTextField4.setEnabled(false);

		jButton1.setText("\u6682\u505c");

		jButton2.setText("\u5220\u9664\u4efb\u52a1");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(33,
																				33,
																				33)
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				91,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(20,
																				20,
																				20)
																		.addComponent(
																				jLabel1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				174,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(166, 166, 166)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addGap(5,
																				5,
																				5)
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				91,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel4)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				159,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(130, Short.MAX_VALUE))
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(46, 46, 46)
										.addComponent(
												jButton2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												215,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												159, Short.MAX_VALUE)
										.addComponent(
												jButton1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												215,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(84, 84, 84)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel1)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jLabel3))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				jTextField3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												52, Short.MAX_VALUE)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																33,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(44, 44, 44)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 727,
						Short.MAX_VALUE)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 280,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jPanel1,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
		// GEN-END:initComponents

	private void deleteClick(java.awt.event.ActionEvent evt) {	
		if(this.tableSelectedIndex==-1){
			JOptionPane.showMessageDialog(null, "请先选择要删除的任务");
		}else{
			int result = JOptionPane.showConfirmDialog(null, "是否需要删除本地文件？");
			System.out.println("result is "+result);
			if(result==0){
				//删除目录中的指定文件
				TaskDownloadInfo info = PublicUtil.wangshidaiList.get(this.tableSelectedIndex);
				File file = new File(PublicUtil.MY_HOME, info.getFile_name());
				file.delete();
				info.setIs_delete(true);
			}

			//从集合中删除指定下标的元素
			PublicUtil.wangshidaiList.remove(this.tableSelectedIndex);
			
			
			JOptionPane.showMessageDialog(null, "删除成功！");

			this.jTextField1.setText("");
			this.jTextField2.setText("");
			this.jTextField3.setText("");
			this.jTextField4.setText("");
			
			
		}
		
		
	}

	private void pauseClick(java.awt.event.ActionEvent evt) {
		if(this.tableSelectedIndex==-1){
			JOptionPane.showMessageDialog(null, "请先选择要暂停的任务");
		}else{
			TaskDownloadInfo info = PublicUtil.wangshidaiList.get(this.tableSelectedIndex);
			
			if(this.jButton1.getText().equals("暂停")){//暂停按钮
				info.setIs_pause(true);
				this.jButton1.setText("继续");
				
			}else{//继续按钮
				info.setIs_pause(false);
				info.interrupt();//叫醒它！！！
				this.jButton1.setText("暂停");
			}
			
			
		}
		
	}

	private void jTable1MousePressed(java.awt.event.MouseEvent evt) {
		// 暂停刷新table
		this.isRefresh = false;

		// 获取表格的选择行
		int selectRow = this.jTable1.getSelectedRow();
		this.tableSelectedIndex = selectRow;
		
		// 从集合中取出对应行的TaskDownloadInfo对象
		TaskDownloadInfo info = PublicUtil.wangshidaiList.get(selectRow);

		this.jTextField1.setText(info.getFile_name());
		this.jTextField2.setText(info.getFile_size() + "b");

		String statusStr = info.isIs_ok() ? "已完成" : "下载中";
		String paswString = "暂停中";
		if(info.isIs_pause()) {
			this.jTextField3.setText(paswString);
		}else {
			this.jTextField3.setText(statusStr);
		}

		this.jTextField4.setText(info.getFile_date());

		// 恢复刷新table
		this.isRefresh = true;
		if(info.isIs_pause()) {
			this.jButton1.setText("暂停");
		}else {
			this.jButton1.setText("继续");
		}
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	// End of variables declaration//GEN-END:variables

}