/*
 * MainView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLEncoder;
import java.net.UnknownHostException;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import cn.hutool.json.JSONArray;
import cn.hutool.json.JSONObject;
import cn.hutool.json.JSONUtil;

/**
 *
 * @author  __USER__
 */
public class MainView extends javax.swing.JFrame {
	//未来5天天气信息
	static JSONArray future=null;
	
	/** Creates new form MainView */
	public MainView() {
		initComponents();

		//设置窗口居中
		this.setLocationRelativeTo(null);

		//开始加载默认深圳天气数据
		getWeather("深圳");

	}
	
	
	/**
	 * 加载未来5天天气预报的Table
	 */
	private void loadTable(){
		DefaultTableModel tableModel = (DefaultTableModel) this.jTable1
				.getModel();

		while (tableModel.getRowCount() > 0) {
			tableModel.removeRow(0);
		}
		
		for (int i=0; i<5;i++) {
			JSONObject obj=(JSONObject) future.get(i);
			String date=obj.getStr("date");
			String temperature=obj.getStr("temperature");
			String weather=obj.getStr("weather");
			String direct=obj.getStr("direct");
			tableModel.addRow(new Object[]{date,weather,temperature,direct});
		}
	}
	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel2 = new javax.swing.JLabel();
		lb_cityname = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		lb_weather = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		lb_temperature = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		lb_wind_direct = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		lb_wind_power = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		lb_humidity = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u7f51\u65f6\u4ee3\u5929\u6c14\u9884\u62a5");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel1.setText("\u8bf7\u8f93\u5165\u57ce\u5e02");

		jButton1.setText("\u67e5\u8be2");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
			
		
		jLabel2.setText("\u57ce\u5e02\u540d\u79f0\uff1a");

		jLabel4.setText("\u5929\u6c14\uff1a");

		jLabel6.setText("\u6e29\u5ea6\uff1a");

		jLabel8.setText("\u98ce\u5411\uff1a");

		jLabel10.setText("\u98ce\u529b\uff1a");

		jLabel12.setText("\u6e7f\u5ea6\uff1a");

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18));
		jLabel14.setText("\u672a\u67655\u5929\u5929\u6c14\u9884\u62a5");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "日期", "天气", "温度", "风向" }));
		jScrollPane1.setViewportView(jTable1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jLabel14))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(44, 44,
																		44)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addGroup(
																						layout.createSequentialGroup()
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel2)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_cityname,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel8)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_wind_direct,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)))
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel10)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_wind_power,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		jLabel12)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_humidity,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))
																												.addGroup(
																														layout.createSequentialGroup()
																																.addComponent(
																																		jLabel4)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_weather,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		jLabel6)
																																.addPreferredGap(
																																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																																.addComponent(
																																		lb_temperature,
																																		javax.swing.GroupLayout.PREFERRED_SIZE,
																																		71,
																																		javax.swing.GroupLayout.PREFERRED_SIZE))))
																				.addGroup(
																						layout.createSequentialGroup()
																								.addComponent(
																										jLabel1)
																								.addPreferredGap(
																										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																								.addComponent(
																										jTextField1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										230,
																										javax.swing.GroupLayout.PREFERRED_SIZE)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										jButton1,
																										javax.swing.GroupLayout.PREFERRED_SIZE,
																										152,
																										javax.swing.GroupLayout.PREFERRED_SIZE))))
												.addGroup(
														layout.createSequentialGroup()
																.addContainerGap()
																.addComponent(
																		jScrollPane1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		562,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(24, 24,
																		24)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																				.addComponent(
																						jLabel1)
																				.addComponent(
																						jTextField1,
																						javax.swing.GroupLayout.PREFERRED_SIZE,
																						40,
																						javax.swing.GroupLayout.PREFERRED_SIZE)))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(23, 23,
																		23)
																.addComponent(
																		jButton1,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		39,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(26, 26, 26)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														lb_cityname,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel4)
												.addComponent(
														lb_weather,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel6)
												.addComponent(
														lb_temperature,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel8)
												.addComponent(
														lb_wind_direct,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel10)
												.addComponent(
														lb_wind_power,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel12)
												.addComponent(
														lb_humidity,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														25,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(45, 45, 45)
								.addComponent(jLabel14)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										200,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainView().setVisible(true);
			}
		});
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String cityName=jTextField1.getText();
		getWeather(cityName);
	}
	
	/*
	 * 查询城市（cityName）天气预报Js数据信息（contentStr）
	 */
	private void getWeather(String cityName){
		BufferedReader buffReader=null;
		try {
			String urlpath="http://apis.juhe.cn/simpleWeather/query";
			String key="035970c98a5df9ab8a304670841a3f3d";
			//da6704bf6856b896ce1d3d26ba76f486
			//1b6a4aee018241f36f609b87e652d5cb
			
			cityName=URLEncoder.encode(cityName, "utf-8"); //只要是有中文，就必须要进行URL编码
			urlpath+="?city="+cityName+"&key="+key;
			
			URL url=new URL(urlpath);
			HttpURLConnection conn=(HttpURLConnection) url.openConnection();
			conn.connect();
			int status=conn.getResponseCode();
			
			if(status==200){
				InputStream input=conn.getInputStream();
				buffReader=new BufferedReader(new InputStreamReader(input, "utf-8"));
				//使用contentStr接收获取的js数据内容
				String contentStr="";
				while(true){
					contentStr+=buffReader.readLine();
					if(buffReader.readLine()==null){
						break;
					}
				}
				//解析js数据信息
				getJsContent(contentStr);
			}else{
				JOptionPane.showMessageDialog(null, "服务器连接失败");
			}
			
			
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}catch (UnknownHostException e) {
			JOptionPane.showMessageDialog(null, "服务器连接失败");
		}catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}finally{
			try {
				if(buffReader!=null){
					buffReader.close();
				}
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}
	//解析获取到的js数据天气信息
	private void getJsContent(String jsContent){
		JSONObject weatherObject=JSONUtil.parseObj(jsContent);
		String resultcode=weatherObject.getStr("resultcode");
		System.out.println(jsContent);
		
		//error_code:0  		正常
		//error_code:112		请求次数超出
		//error_code:207301		暂不支持该城市
		if("112".equals(resultcode)){
			JOptionPane.showMessageDialog(null, "超过每日可允许请求次数,请更换key值后使用");
			return;
		}
		JSONObject resultOBJ=weatherObject.getJSONObject("result");
		String city=resultOBJ.getStr("city");
		if(city==null){
			JOptionPane.showMessageDialog(null, "无法查询到该城市信息，请重新输入");
		}else{
			JSONObject realTimeobj=resultOBJ.getJSONObject("realtime");
			String temperature=realTimeobj.getStr("temperature");
			String humidity=realTimeobj.getStr("humidity");
			String info=realTimeobj.getStr("info");
			String direct=realTimeobj.getStr("direct");
			String power=realTimeobj.getStr("power");
			
			//当前查询的城市的天气预报
			lb_cityname.setText(city);
			lb_weather.setText(info);
			lb_temperature.setText(temperature+"℃");
			lb_wind_direct.setText(direct);
			lb_wind_power.setText(power);
			lb_humidity.setText(humidity);
			
			//未来5天天气预报
			future=resultOBJ.getJSONArray("future");
			loadTable();
		}
	}
	
	
	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JLabel lb_cityname;
	private javax.swing.JLabel lb_humidity;
	private javax.swing.JLabel lb_temperature;
	private javax.swing.JLabel lb_weather;
	private javax.swing.JLabel lb_wind_direct;
	private javax.swing.JLabel lb_wind_power;
	// End of variables declaration//GEN-END:variables

}