/*
 * ChatView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.io.IOException;
import java.io.ObjectOutputStream;

import javax.swing.JFrame;

import cn.wangshidai.entity.MessageInfo;
import cn.wangshidai.entity.UserInfo;
import cn.wangshidai.util.RefreshMessageThread;

/**
 *
 * @author  __USER__
 */
public class ChatView extends javax.swing.JFrame {

	//接收人（对方）
	private UserInfo chatUserInfo;
	
	/** Creates new form ChatView */
	public ChatView(UserInfo chatUserInfo) {
		this.chatUserInfo = chatUserInfo;
		
		//加载窗口上的UI组件
		initComponents();
		
		//设置title
		this.setTitle("与"+this.chatUserInfo.getUser_name()+"的聊天");
		
		//禁用窗口上的关闭按钮
		this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
		
		//开启一条线程去显示聊天记录内容
		new Thread(new ShowMessageContent()).start();
	}
	
	private class ShowMessageContent implements Runnable{
		
		@Override
		public void run() {
			while (true) {
				RefreshMessageThread refreshThread = RefreshMessageThread.getObject();
				
				boolean hasKey = refreshThread.messageMap.containsKey(chatUserInfo.getUser_name());
				if(hasKey){
					StringBuffer messageSB = refreshThread.messageMap.get(chatUserInfo.getUser_name());	
					text_content.setText(messageSB.toString());
				}
				
				
				
				try {
					Thread.sleep(500);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
		}
		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane1 = new javax.swing.JScrollPane();
		text_chat = new javax.swing.JTextArea();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane2 = new javax.swing.JScrollPane();
		text_content = new javax.swing.JTextArea();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u4e0e\u5f20\u4e09\u7684\u804a\u5929");
		setResizable(false);

		text_chat.setColumns(20);
		text_chat.setRows(5);
		jScrollPane1.setViewportView(text_chat);

		jButton1.setText("\u5173\u95ed");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u53d1\u9001");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		text_content.setColumns(20);
		text_content.setEditable(false);
		text_content.setRows(5);
		jScrollPane2.setViewportView(text_content);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1,
						javax.swing.GroupLayout.DEFAULT_SIZE, 609,
						Short.MAX_VALUE)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(465, Short.MAX_VALUE)
								.addComponent(jButton1).addGap(18, 18, 18)
								.addComponent(jButton2).addContainerGap())
				.addComponent(jScrollPane2,
						javax.swing.GroupLayout.DEFAULT_SIZE, 609,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addComponent(jScrollPane2,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										270, Short.MAX_VALUE)
								.addGap(18, 18, 18)
								.addComponent(jScrollPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										137,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jButton2)
												.addComponent(jButton1))
								.addGap(14, 14, 14)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		this.setVisible(false);
	}
	
	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		String msg = this.text_chat.getText();
		
		//每次调用getObject()方法，都是拿到的同一个对象
		RefreshMessageThread refreshThread = RefreshMessageThread.getObject();
		
		//准备一个MessageInfo消息对象
		MessageInfo msgInfo = new MessageInfo();
		msgInfo.setSend_user(refreshThread.getCurrentUserInfo().getUser_name());//发送人
		msgInfo.setReceive_user(this.chatUserInfo.getUser_name());				//接收人
		msgInfo.setMsg_content(msg);
		
		//System.out.println("您对"+this.chatUserInfo.getUser_name()+"说:"+msg);
		boolean hasKey = refreshThread.messageMap.containsKey(msgInfo.getReceive_user());
		if(!hasKey){//key不存在
			StringBuffer sb = new StringBuffer();
			sb.append("您对"+this.chatUserInfo.getUser_name()+"说:"+msg+"\n");
			refreshThread.messageMap.put(msgInfo.getReceive_user(), sb);
		}else{//key存在
			StringBuffer sb = refreshThread.messageMap.get(msgInfo.getReceive_user());
			sb.append("您对"+this.chatUserInfo.getUser_name()+"说:"+msg+"\n");
		}
		
		try {
			//使用socket搞一个输出流将msgInfo对象发给服务器
			ObjectOutputStream out = new ObjectOutputStream(refreshThread.getClientSocket().getOutputStream());
			out.writeObject(msgInfo);
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} finally{
			//要关闭socket吗？？
		}
		
		
	}
	

//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new ChatView().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JTextArea text_chat;
	private javax.swing.JTextArea text_content;
	// End of variables declaration//GEN-END:variables

}