/*
 * MainView.java
 *
 * Created on __DATE__, __TIME__
 */

package cn.wangshidai.view;

import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

import cn.wangshidai.entity.UserInfo;

/**
 *
 * @author  __USER__
 */
public class MainView extends javax.swing.JFrame {

	private List<UserInfo> userList;		//所有用户列表
	private UserInfo currentUserInfo;		//当前登录用户的信息
	
	/** Creates new form MainView */
	public MainView(List<UserInfo> userList,UserInfo currentUserInfo) {
		this.userList = userList;
		this.currentUserInfo = currentUserInfo;
		
		//加载当前页面的所有UI组件
		initComponents();
		
		//设置title
		this.setTitle("欢迎您！" + this.currentUserInfo.getUser_name());

		//加载在线用户列表
		loadList();
	}

	private void loadList() {
		DefaultListModel model = new DefaultListModel();
		
		for (UserInfo userInfo : userList) {
			model.addElement(userInfo.getUser_name());
		}

		this.jList1.setModel(model);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

jScrollPane1 = new javax.swing.JScrollPane();
jList1 = new javax.swing.JList();

setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
setTitle("\u7f51\u65f6\u4ee3\u804a\u5929\u5ba4");
setResizable(false);

//jList1.setModel([]);
jList1.addMouseListener(new java.awt.event.MouseAdapter() {
public void mousePressed(java.awt.event.MouseEvent evt) {
jList1MousePressed(evt);
}
});
jScrollPane1.setViewportView(jList1);

javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
getContentPane().setLayout(layout);
layout.setHorizontalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
);
layout.setVerticalGroup(
layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
);

pack();
}// </editor-fold>

	//GEN-END:initComponents
	private void jList1MousePressed(java.awt.event.MouseEvent evt) {
		int index = this.jList1.getSelectedIndex();
		System.out.println("index is " + index);
		UserInfo chatUserInfo = this.userList.get(index);
		
		ChatView view = new ChatView(chatUserInfo);
		view.setVisible(true);
		
	}

//	/**
//	 * @param args the command line arguments
//	 */
//	public static void main(String args[]) {
//		java.awt.EventQueue.invokeLater(new Runnable() {
//			public void run() {
//				new MainView().setVisible(true);
//			}
//		});
//	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JList jList1;
	private javax.swing.JScrollPane jScrollPane1;
	// End of variables declaration//GEN-END:variables

}